version: "3.7"

networks:
  dev: # virtual network name
    driver: bridge
    ipam:
     config: # here, we define our ip space
       - subnet: 192.10.100.0/28

# this is a YAML anchor to avoid repetition
x-logging: &logging
  logging:
    driver: loki
    options: # note: the ip is the ip we will assign later to loki in this file
      loki-url: "http://192.10.100.2:3100/loki/api/v1/push"
      # loki-url: "http://loki:3100/loki/api/v1/push"

services:
  loki:
    image: grafana/loki:2.0.0
    container_name: "loki.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${LOKI_PORT}:3100"
    # command: -config.file=/etc/loki/local-config.yaml
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.2
    volumes:
      - ./.docker/loki-config.yaml:/etc/loki/local-config.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  promtail:
    image: grafana/promtail:2.0.0
    container_name: "promtail.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${PROMTAIL_PORT}:7980"
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.3
    volumes:
      - /var/log:/var/log
      - ./.docker/promtail-config.yaml:/etc/promtail/config.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${GF_PORT}:3000"
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_DEFAULT_THEME: ${GF_USERS_DEFAULT_THEME}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
      GF_USERS_ALLOW_ORG_CREATE: ${GF_USERS_ALLOW_ORG_CREATE}
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_INSTALL_PLUGINS: ${GF_INSTALL_PLUGINS}
    depends_on:
      - promtail
      - loki

  gitea:
    <<: *logging
    image: gitea/gitea:latest
    container_name: "gitea.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: ${GITEA_DATABASE}
      GITEA__database__USER: ${DATABASE_USERNAME}
      GITEA__database__PASSWD: ${DATABASE_PASSWORD}
      DEFAULT_THEME: ${GITEA_THEME}
      # HTTP_PORT: ${GITEA_PORT}
    restart: unless-stopped
    volumes:
      - ./storage/gitea.data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:7433"
      - "2222:22"
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.5
    depends_on:
      - db
      - loki

  adminer:
    image: adminer:latest
    container_name: "adminer.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '${ADMINER_PORT}:8080'
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.6
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    # <<: *logging
    image: mariadb:latest
    container_name: "db.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3306:3306'
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.7
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_APP: ${APP_DATABASE}
      DATABASE_GITEA: ${GITEA_DATABASE}
    volumes:
      - ./storage/db.data:/var/lib/mysql
      - ./.docker/db/init:/docker-entrypoint-initdb.d:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  maildev:
    image: djfarrelly/maildev
    container_name: "mail.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    environment:
      MAILDEV_SMTP_PORT: ${SMTP_PORT}
      MAILDEV_WEB_PORT: ${WEBMAIL_PORT}
    ports:
      - "${SMTP_PORT}:25"
      - "${WEBMAIL_PORT}:80"
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.8
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  php:
    <<: *logging
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: ${ENVIRONMENT}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: "php.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    environment:
      APP_NAME: ${APP_NAME}
      ENVIRONMENT: ${ENVIRONMENT}
      LISTEN: ${API_PORT}
    entrypoint: sh /bin/entrypoint.sh php-fpm
    volumes:
      - ./.docker/php/msmtprc:/etc/msmtprc:ro
      - ./src/backend:/var/www/backend
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/php/docker-entrypoint.sh:/bin/entrypoint.sh:ro
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.9
    expose:
      - 9000
    ports:
      - '${API_PORT}:${API_PORT}'
    links:
      - maildev:maildev

  nodejs:
    #<<: *logging
    build:
      context: .
      dockerfile: ./.docker/nodejs/Dockerfile
      target: ${ENVIRONMENT}
    container_name: "nodejs.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    environment:
      APP_NAME: ${APP_NAME}
      ENVIRONMENT: ${ENVIRONMENT}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.10
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    volumes:
      - ./src/frontend:/var/www/frontend
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nginx:
    <<: *logging
    image: nginx
    container_name: "nginx.${APP_NAME}"
    restart: unless-stopped
    env_file: ./.env
    environment:
      APP_NAME: ${APP_NAME}
      ENVIRONMENT: ${ENVIRONMENT}
      NGINX_PORT: ${NGINX_PORT}
      API_PORT: ${API_PORT}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - php
      - loki
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates:rw,cached
      - ./src/frontend:/var/www/frontend
      - ./src/backend:/var/www/backend
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      dev: # this is the place where we assign the static ipv4 address
        ipv4_address: 192.10.100.11
