version: "3.6"
services:
    app:
      restart: unless-stopped
      container_name: example-app
      image: debian:jessie
      entrypoint: /bin/bash
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./application:/var/www/html
        - database-storage:/var/lib/mysql
    db:
      restart: unless-stopped
      container_name: example-db
      image: mariadb:10.4
      depends_on:
        - app
      environment:
        - MYSQL_ROOT_PASSWORD=happyplace
        - MYSQL_DATABASE=happyplace
        - MYSQL_USER=happyplace
        - MYSQL_PASSWORD=happyplace
      ports:
        - "8083:3306"
      volumes:
        - database-storage:/var/lib/mysql
    www:
      restart: unless-stopped
      container_name: example-www
      build:
        context: ./.docker
        dockerfile: nginx.dockerfile
      ports:
        - "80:80"
      depends_on:
        - app
        - php
      volumes:
        - ./application:/var/www/html
    php:
      restart: unless-stopped
      container_name: example-php
      build:
        context: ./.docker
        dockerfile: php.dockerfile
      expose:
          - 9000
      volumes:
        - ./application:/var/www/html
    cli:
      restart: unless-stopped
      container_name: example-cli
      build:
        context: ./.docker
        dockerfile: php-cli.dockerfile
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./application:/var/www/html
    adminer:
      restart: unless-stopped
      container_name: example-dba
      image: adminer
      ports:
        - 8080:8080
      depends_on:
        - db
        - php
        - app
volumes:
  database-storage:
