version: "3.7"

networks:
  dev:
    external: false

services:
  loki:
    image: grafana/loki:2.0.0
    container_name: "loki"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${LOKI_PORT}:3100"
    # command: -config.file=/etc/loki/local-config.yaml
    networks:
      - dev
    volumes:
      - ./.docker/loki-config.yaml:/etc/loki/local-config.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # For this to work you need to install the logging driver
    # See https://grafana.com/docs/loki/latest/clients/docker-driver/
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  promtail:
    image: grafana/promtail:2.0.0
    container_name: "promtail"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${PROMTAIL_PORT}:7980"
    networks:
      - dev
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log:/var/log
      - ./.docker/promtail-config.yaml:/etc/promtail/config.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: unless-stopped
    ports:
      - "${GF_PORT}:3000"
    networks:
      - dev
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_DEFAULT_THEME: ${GF_USERS_DEFAULT_THEME}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
      GF_USERS_ALLOW_ORG_CREATE: ${GF_USERS_ALLOW_ORG_CREATE}
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_INSTALL_PLUGINS: ${GF_INSTALL_PLUGINS}
    depends_on:
      - loki
      - promtail
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/"

  gitea:
    image: gitea/gitea:latest
    container_name: "gitea"
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: ${GITEA_DATABASE}
      GITEA__database__USER: ${DATABASE_USERNAME}
      GITEA__database__PASSWD: ${DATABASE_PASSWORD}
      DEFAULT_THEME: ${GITEA_THEME}
      HTTP_PORT: ${GITEA_PORT}
    restart: unless-stopped
    volumes:
      - ./storage/gitea.data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:${GITEA_PORT}"
      - "2222:22"
    networks:
      - dev
    depends_on:
      - db

  adminer:
    image: adminer:latest
    container_name: "adminer"
    restart: unless-stopped
    ports:
      - '${ADMINER_PORT}:8080'
    networks:
      - dev
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: "db"
    restart: unless-stopped
    ports:
      - '3306:3306'
    networks:
      - dev
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_APP: ${APP_DATABASE}
      DATABASE_GITEA: ${GITEA_DATABASE}
    volumes:
      - ./storage/db.data:/var/lib/mysql
      - ./.docker/db/init:/docker-entrypoint-initdb.d:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/"

  mail:
    image: schickling/mailcatcher:latest
    container_name: "mail"
    restart: unless-stopped
    ports:
      - "${WEBMAIL_PORT}:1080"
    networks:
      - dev
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/"

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: ${TARGET}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: "php"
    volumes:
      - ./src/backend:/var/www/backend
    networks:
      - dev
    ports:
      - '${PHPSRV_PORT}:9000'
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/"

  nodejs:
    build:
      context: .
      dockerfile: ./.docker/nodejs/Dockerfile
      target: ${TARGET}
    container_name: "nodejs"
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - dev
    ports:
      - '${NODE_PORT}:7090'
    volumes:
      - ./src/frontend:/var/www/frontend
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/"

  nginx:
    build: ./.docker/nginx/
    container_name: "nginx"
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./src/frontend:/var/www/frontend
      - ./src/backend:/var/www/backend
    networks:
      - dev
    # For this to work you need to install the logging driver
    # See https://grafana.com/docs/loki/latest/clients/docker-driver/
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
