version: "3.6"
services:
    app:
      container_name: app
      image: debian:jessie
      entrypoint: /bin/bash
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./applications:/var/www/html
        - database-storage:/var/lib/mysql
    mariadb:
      container_name: mariadb
      image: mariadb:10.4
      restart: always
      depends_on:
        - app
      environment:
        - MYSQL_ROOT_PASSWORD=happyplace
        - MYSQL_DATABASE=happyplace
        - MYSQL_USER=happyplace
        - MYSQL_PASSWORD=happyplace
      ports:
        - "8083:3306"
      volumes:
        - database-storage:/var/lib/mysql
    webserver:
      container_name: webserver
      build:
        context: ./.docker
        dockerfile: nginx.dockerfile
      ports:
        - "80:80"
      depends_on:
        - app
        - php
      volumes:
        - ./applications:/var/www/html
    php:
      container_name: php
      build:
        context: ./.docker
        dockerfile: php.dockerfile
      expose:
          - 9000
      volumes:
        - ./applications:/var/www/html
    cli:
      container_name: cli
      build:
        context: ./.docker
        dockerfile: php-cli.dockerfile
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./applications:/var/www/html
    adminer:
      container_name: adminer
      image: adminer
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - mariadb
        - php
        - app
volumes:
  database-storage:
