version: "3.9"
services:
    web:
      build: ./nginx/
      container_name: web
      ports:
        - "80:80"
      depends_on:
          - php
      volumes:
        - type: bind
          source: ./application/html
          target: /var/www/html
    db:
      image: mariadb:10.4
      container_name: db
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=happyplace
        - MYSQL_DATABASE=happyplace
        - MYSQL_USER=happyplace
        - MYSQL_PASSWORD=happyplace
      ports:
        - "8083:3306"
      volumes:
        - type: volume
          source: dbstorage
          target: /var/lib/mysql
    php:
      build: ./php/
      expose:
          - 9000
      container_name: php
    cli:
      build: ./php-cli/
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      container_name: cli
    adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - db
        - php
volumes:
  dbstorage:
