server:
  http_listen_port: 7980
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: container-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: container
      host: localhost
    __path__: /var/lib/docker/containers/*/*.log
    # __path__ denotes the path of the actual log file whose logs will be scraped
    # and shipped to loki indexed with the above labels
